name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    step: 
      -uses: actions/checkout@main
      -name: Publish to registry
       uses: elhgohr/Publish-Docker-Github-Action@v5
       with:
        registry: docker.pkg.github.com
        name: docker.pkg.github.com//ChuikinaMaria/top-api/top-api
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        default_branch: main
        tags: "develop"
